spring:
  application:
    name: web-service
server:
  port: 8001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
zuul:
  ignored-services: '*'
  routes:
    backend-service: 'api/**'
    backend-service-2: 'api2/**'